name: dart_godot
description: DartGodot = Dart + Godot + MahdiSml
version: 0.1.0
homepage: https://github.com/mahdisml/DartGodot

environment:
  sdk: '>=2.8.1 <3.0.0'

dependencies:
  js: ^0.6.2

dev_dependencies:
  pedantic: ^1.9.0
